'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CAccordionCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CAccordion as CAccordionElement, defineCustomElement as defineCAccordion } from "@componentry-ui/stencil/dist/components/c-accordion.js";

export type CAccordionEvents = {
    onCShow: EventName<CAccordionCustomEvent<void>>,
    onCAfterShow: EventName<CAccordionCustomEvent<void>>,
    onCHide: EventName<CAccordionCustomEvent<void>>,
    onCAfterHide: EventName<CAccordionCustomEvent<void>>
};

export const CAccordion: StencilReactComponent<CAccordionElement, CAccordionEvents, Components.CAccordion> = /*@__PURE__*/ createComponent<CAccordionElement, CAccordionEvents, Components.CAccordion>({
    tagName: 'c-accordion',
    elementClass: CAccordionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCShow: 'c-show',
        onCAfterShow: 'cAfterShow',
        onCHide: 'cHide',
        onCAfterHide: 'cAfterHide'
    } as CAccordionEvents,
    defineCustomElement: defineCAccordion
});
