'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CAlertCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CAlert as CAlertElement, defineCustomElement as defineCAlert } from "@componentry-ui/stencil/dist/components/c-alert.js";

export type CAlertEvents = {
    onCShow: EventName<CAlertCustomEvent<void>>,
    onCAfterShow: EventName<CAlertCustomEvent<void>>,
    onCHide: EventName<CAlertCustomEvent<void>>,
    onCAfterHide: EventName<CAlertCustomEvent<void>>
};

export const CAlert: StencilReactComponent<CAlertElement, CAlertEvents, Components.CAlert> = /*@__PURE__*/ createComponent<CAlertElement, CAlertEvents, Components.CAlert>({
    tagName: 'c-alert',
    elementClass: CAlertElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCShow: 'cShow',
        onCAfterShow: 'cAfterShow',
        onCHide: 'cHide',
        onCAfterHide: 'cAfterHide'
    } as CAlertEvents,
    defineCustomElement: defineCAlert
});
