'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CAvatarCustomEvent } from "@componentry/stencil";
import type { Components } from "@componentry/stencil/dist/components";
import { CAvatar as CAvatarElement, defineCustomElement as defineCAvatar } from "@componentry/stencil/dist/components/c-avatar.js";

export type CAvatarEvents = { onCError: EventName<CAvatarCustomEvent<void>> };

export const CAvatar: StencilReactComponent<CAvatarElement, CAvatarEvents, Components.CAvatar> = /*@__PURE__*/ createComponent<CAvatarElement, CAvatarEvents, Components.CAvatar>({
    tagName: 'c-avatar',
    elementClass: CAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCError: 'cError' } as CAvatarEvents,
    defineCustomElement: defineCAvatar
});
