'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry/stencil/dist/components";
import { CBadge as CBadgeElement, defineCustomElement as defineCBadge } from "@componentry/stencil/dist/components/c-badge.js";

export type CBadgeEvents = NonNullable<unknown>;

export const CBadge: StencilReactComponent<CBadgeElement, CBadgeEvents, Components.CBadge> = /*@__PURE__*/ createComponent<CBadgeElement, CBadgeEvents, Components.CBadge>({
    tagName: 'c-badge',
    elementClass: CBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CBadgeEvents,
    defineCustomElement: defineCBadge
});
