'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CBreadcrumbItem as CBreadcrumbItemElement, defineCustomElement as defineCBreadcrumbItem } from "@componentry-ui/stencil/dist/components/c-breadcrumb-item.js";

export type CBreadcrumbItemEvents = NonNullable<unknown>;

export const CBreadcrumbItem: StencilReactComponent<CBreadcrumbItemElement, CBreadcrumbItemEvents, Components.CBreadcrumbItem> = /*@__PURE__*/ createComponent<CBreadcrumbItemElement, CBreadcrumbItemEvents, Components.CBreadcrumbItem>({
    tagName: 'c-breadcrumb-item',
    elementClass: CBreadcrumbItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CBreadcrumbItemEvents,
    defineCustomElement: defineCBreadcrumbItem
});
