'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CBreadcrumb as CBreadcrumbElement, defineCustomElement as defineCBreadcrumb } from "@componentry-ui/stencil/dist/components/c-breadcrumb.js";

export type CBreadcrumbEvents = NonNullable<unknown>;

export const CBreadcrumb: StencilReactComponent<CBreadcrumbElement, CBreadcrumbEvents, Components.CBreadcrumb> = /*@__PURE__*/ createComponent<CBreadcrumbElement, CBreadcrumbEvents, Components.CBreadcrumb>({
    tagName: 'c-breadcrumb',
    elementClass: CBreadcrumbElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CBreadcrumbEvents,
    defineCustomElement: defineCBreadcrumb
});
