'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CButtonGroupText as CButtonGroupTextElement, defineCustomElement as defineCButtonGroupText } from "@componentry-ui/stencil/dist/components/c-button-group-text.js";

export type CButtonGroupTextEvents = NonNullable<unknown>;

export const CButtonGroupText: StencilReactComponent<CButtonGroupTextElement, CButtonGroupTextEvents, Components.CButtonGroupText> = /*@__PURE__*/ createComponent<CButtonGroupTextElement, CButtonGroupTextEvents, Components.CButtonGroupText>({
    tagName: 'c-button-group-text',
    elementClass: CButtonGroupTextElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CButtonGroupTextEvents,
    defineCustomElement: defineCButtonGroupText
});
