'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CButtonCustomEvent } from "@componentry/stencil";
import type { Components } from "@componentry/stencil/dist/components";
import { CButton as CButtonElement, defineCustomElement as defineCButton } from "@componentry/stencil/dist/components/c-button.js";

export type CButtonEvents = {
    onCBlur: EventName<CButtonCustomEvent<void>>,
    onCFocus: EventName<CButtonCustomEvent<void>>,
    onCInvalid: EventName<CButtonCustomEvent<void>>
};

export const CButton: StencilReactComponent<CButtonElement, CButtonEvents, Components.CButton> = /*@__PURE__*/ createComponent<CButtonElement, CButtonEvents, Components.CButton>({
    tagName: 'c-button',
    elementClass: CButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCBlur: 'cBlur',
        onCFocus: 'cFocus',
        onCInvalid: 'cInvalid'
    } as CButtonEvents,
    defineCustomElement: defineCButton
});
