'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry/stencil/dist/components";
import { CButtonGroup as CButtonGroupElement, defineCustomElement as defineCButtonGroup } from "@componentry/stencil/dist/components/c-button-group.js";

export type CButtonGroupEvents = NonNullable<unknown>;

export const CButtonGroup: StencilReactComponent<CButtonGroupElement, CButtonGroupEvents, Components.CButtonGroup> = /*@__PURE__*/ createComponent<CButtonGroupElement, CButtonGroupEvents, Components.CButtonGroup>({
    tagName: 'c-button-group',
    elementClass: CButtonGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CButtonGroupEvents,
    defineCustomElement: defineCButtonGroup
});
