'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry/stencil/dist/components";
import { CButtonGroupSeparator as CButtonGroupSeparatorElement, defineCustomElement as defineCButtonGroupSeparator } from "@componentry/stencil/dist/components/c-button-group-separator.js";

export type CButtonGroupSeparatorEvents = NonNullable<unknown>;

export const CButtonGroupSeparator: StencilReactComponent<CButtonGroupSeparatorElement, CButtonGroupSeparatorEvents, Components.CButtonGroupSeparator> = /*@__PURE__*/ createComponent<CButtonGroupSeparatorElement, CButtonGroupSeparatorEvents, Components.CButtonGroupSeparator>({
    tagName: 'c-button-group-separator',
    elementClass: CButtonGroupSeparatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CButtonGroupSeparatorEvents,
    defineCustomElement: defineCButtonGroupSeparator
});
