'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry/stencil/dist/components";
import { CCardAction as CCardActionElement, defineCustomElement as defineCCardAction } from "@componentry/stencil/dist/components/c-card-action.js";

export type CCardActionEvents = NonNullable<unknown>;

export const CCardAction: StencilReactComponent<CCardActionElement, CCardActionEvents, Components.CCardAction> = /*@__PURE__*/ createComponent<CCardActionElement, CCardActionEvents, Components.CCardAction>({
    tagName: 'c-card-action',
    elementClass: CCardActionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CCardActionEvents,
    defineCustomElement: defineCCardAction
});
