'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry/stencil/dist/components";
import { CCard as CCardElement, defineCustomElement as defineCCard } from "@componentry/stencil/dist/components/c-card.js";

export type CCardEvents = NonNullable<unknown>;

export const CCard: StencilReactComponent<CCardElement, CCardEvents, Components.CCard> = /*@__PURE__*/ createComponent<CCardElement, CCardEvents, Components.CCard>({
    tagName: 'c-card',
    elementClass: CCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CCardEvents,
    defineCustomElement: defineCCard
});
