'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CCarouselItem as CCarouselItemElement, defineCustomElement as defineCCarouselItem } from "@componentry-ui/stencil/dist/components/c-carousel-item.js";

export type CCarouselItemEvents = NonNullable<unknown>;

export const CCarouselItem: StencilReactComponent<CCarouselItemElement, CCarouselItemEvents, Components.CCarouselItem> = /*@__PURE__*/ createComponent<CCarouselItemElement, CCarouselItemEvents, Components.CCarouselItem>({
    tagName: 'c-carousel-item',
    elementClass: CCarouselItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CCarouselItemEvents,
    defineCustomElement: defineCCarouselItem
});
