'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CCardTitle as CCardTitleElement, defineCustomElement as defineCCardTitle } from "@componentry-ui/stencil/dist/components/c-card-title.js";

export type CCardTitleEvents = NonNullable<unknown>;

export const CCardTitle: StencilReactComponent<CCardTitleElement, CCardTitleEvents, Components.CCardTitle> = /*@__PURE__*/ createComponent<CCardTitleElement, CCardTitleEvents, Components.CCardTitle>({
    tagName: 'c-card-title',
    elementClass: CCardTitleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CCardTitleEvents,
    defineCustomElement: defineCCardTitle
});
