'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CCardContent as CCardContentElement, defineCustomElement as defineCCardContent } from "@componentry-ui/stencil/dist/components/c-card-content.js";

export type CCardContentEvents = NonNullable<unknown>;

export const CCardContent: StencilReactComponent<CCardContentElement, CCardContentEvents, Components.CCardContent> = /*@__PURE__*/ createComponent<CCardContentElement, CCardContentEvents, Components.CCardContent>({
    tagName: 'c-card-content',
    elementClass: CCardContentElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CCardContentEvents,
    defineCustomElement: defineCCardContent
});
