'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry/stencil/dist/components";
import { CCardHeader as CCardHeaderElement, defineCustomElement as defineCCardHeader } from "@componentry/stencil/dist/components/c-card-header.js";

export type CCardHeaderEvents = NonNullable<unknown>;

export const CCardHeader: StencilReactComponent<CCardHeaderElement, CCardHeaderEvents, Components.CCardHeader> = /*@__PURE__*/ createComponent<CCardHeaderElement, CCardHeaderEvents, Components.CCardHeader>({
    tagName: 'c-card-header',
    elementClass: CCardHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CCardHeaderEvents,
    defineCustomElement: defineCCardHeader
});
