'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CCardFooter as CCardFooterElement, defineCustomElement as defineCCardFooter } from "@componentry-ui/stencil/dist/components/c-card-footer.js";

export type CCardFooterEvents = NonNullable<unknown>;

export const CCardFooter: StencilReactComponent<CCardFooterElement, CCardFooterEvents, Components.CCardFooter> = /*@__PURE__*/ createComponent<CCardFooterElement, CCardFooterEvents, Components.CCardFooter>({
    tagName: 'c-card-footer',
    elementClass: CCardFooterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CCardFooterEvents,
    defineCustomElement: defineCCardFooter
});
