'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CCarouselCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CCarousel as CCarouselElement, defineCustomElement as defineCCarousel } from "@componentry-ui/stencil/dist/components/c-carousel.js";

export type CCarouselEvents = { onCSlideChange: EventName<CCarouselCustomEvent<{ index: number; slide: HTMLElement; }>> };

export const CCarousel: StencilReactComponent<CCarouselElement, CCarouselEvents, Components.CCarousel> = /*@__PURE__*/ createComponent<CCarouselElement, CCarouselEvents, Components.CCarousel>({
    tagName: 'c-carousel',
    elementClass: CCarouselElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCSlideChange: 'cSlideChange' } as CCarouselEvents,
    defineCustomElement: defineCCarousel
});
