'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry/stencil/dist/components";
import { CCardDescription as CCardDescriptionElement, defineCustomElement as defineCCardDescription } from "@componentry/stencil/dist/components/c-card-description.js";

export type CCardDescriptionEvents = NonNullable<unknown>;

export const CCardDescription: StencilReactComponent<CCardDescriptionElement, CCardDescriptionEvents, Components.CCardDescription> = /*@__PURE__*/ createComponent<CCardDescriptionElement, CCardDescriptionEvents, Components.CCardDescription>({
    tagName: 'c-card-description',
    elementClass: CCardDescriptionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CCardDescriptionEvents,
    defineCustomElement: defineCCardDescription
});
