'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CCheckboxCustomEvent } from "@componentry/stencil";
import type { Components } from "@componentry/stencil/dist/components";
import { CCheckbox as CCheckboxElement, defineCustomElement as defineCCheckbox } from "@componentry/stencil/dist/components/c-checkbox.js";

export type CCheckboxEvents = {
    onCBlur: EventName<CCheckboxCustomEvent<void>>,
    onCChange: EventName<CCheckboxCustomEvent<void>>,
    onCFocus: EventName<CCheckboxCustomEvent<void>>,
    onCInput: EventName<CCheckboxCustomEvent<void>>,
    onCInvalid: EventName<CCheckboxCustomEvent<void>>
};

export const CCheckbox: StencilReactComponent<CCheckboxElement, CCheckboxEvents, Components.CCheckbox> = /*@__PURE__*/ createComponent<CCheckboxElement, CCheckboxEvents, Components.CCheckbox>({
    tagName: 'c-checkbox',
    elementClass: CCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCBlur: 'cBlur',
        onCChange: 'cChange',
        onCFocus: 'cFocus',
        onCInput: 'cInput',
        onCInvalid: 'cInvalid'
    } as CCheckboxEvents,
    defineCustomElement: defineCCheckbox
});
