'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CComboboxItemCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CComboboxItem as CComboboxItemElement, defineCustomElement as defineCComboboxItem } from "@componentry-ui/stencil/dist/components/c-combobox-item.js";

export type CComboboxItemEvents = { onItemSelect: EventName<CComboboxItemCustomEvent<string>> };

export const CComboboxItem: StencilReactComponent<CComboboxItemElement, CComboboxItemEvents, Components.CComboboxItem> = /*@__PURE__*/ createComponent<CComboboxItemElement, CComboboxItemEvents, Components.CComboboxItem>({
    tagName: 'c-combobox-item',
    elementClass: CComboboxItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onItemSelect: 'itemSelect' } as CComboboxItemEvents,
    defineCustomElement: defineCComboboxItem
});
