'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CComboboxSeparator as CComboboxSeparatorElement, defineCustomElement as defineCComboboxSeparator } from "@componentry-ui/stencil/dist/components/c-combobox-separator.js";

export type CComboboxSeparatorEvents = NonNullable<unknown>;

export const CComboboxSeparator: StencilReactComponent<CComboboxSeparatorElement, CComboboxSeparatorEvents, Components.CComboboxSeparator> = /*@__PURE__*/ createComponent<CComboboxSeparatorElement, CComboboxSeparatorEvents, Components.CComboboxSeparator>({
    tagName: 'c-combobox-separator',
    elementClass: CComboboxSeparatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CComboboxSeparatorEvents,
    defineCustomElement: defineCComboboxSeparator
});
