'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CComboboxGroup as CComboboxGroupElement, defineCustomElement as defineCComboboxGroup } from "@componentry-ui/stencil/dist/components/c-combobox-group.js";

export type CComboboxGroupEvents = NonNullable<unknown>;

export const CComboboxGroup: StencilReactComponent<CComboboxGroupElement, CComboboxGroupEvents, Components.CComboboxGroup> = /*@__PURE__*/ createComponent<CComboboxGroupElement, CComboboxGroupEvents, Components.CComboboxGroup>({
    tagName: 'c-combobox-group',
    elementClass: CComboboxGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CComboboxGroupEvents,
    defineCustomElement: defineCComboboxGroup
});
