'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CComboboxCustomEvent, type ComboboxValueChangeDetail } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CCombobox as CComboboxElement, defineCustomElement as defineCCombobox } from "@componentry-ui/stencil/dist/components/c-combobox.js";

export type CComboboxEvents = {
    onValueChange: EventName<CComboboxCustomEvent<ComboboxValueChangeDetail>>,
    onOpenChange: EventName<CComboboxCustomEvent<boolean>>,
    onInputChange: EventName<CComboboxCustomEvent<string>>,
    onComboboxBlur: EventName<CComboboxCustomEvent<void>>,
    onComboboxFocus: EventName<CComboboxCustomEvent<void>>
};

export const CCombobox: StencilReactComponent<CComboboxElement, CComboboxEvents, Components.CCombobox> = /*@__PURE__*/ createComponent<CComboboxElement, CComboboxEvents, Components.CCombobox>({
    tagName: 'c-combobox',
    elementClass: CComboboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onValueChange: 'valueChange',
        onOpenChange: 'openChange',
        onInputChange: 'inputChange',
        onComboboxBlur: 'comboboxBlur',
        onComboboxFocus: 'comboboxFocus'
    } as CComboboxEvents,
    defineCustomElement: defineCCombobox
});
