'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CDialogCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CDialog as CDialogElement, defineCustomElement as defineCDialog } from "@componentry-ui/stencil/dist/components/c-dialog.js";

export type CDialogEvents = {
    onCShow: EventName<CDialogCustomEvent<void>>,
    onCAfterShow: EventName<CDialogCustomEvent<void>>,
    onCHide: EventName<CDialogCustomEvent<void>>,
    onCAfterHide: EventName<CDialogCustomEvent<void>>,
    onCInitialFocus: EventName<CDialogCustomEvent<void>>,
    onCRequestClose: EventName<CDialogCustomEvent<{ source: "close-button" | "keyboard" | "overlay"; }>>
};

export const CDialog: StencilReactComponent<CDialogElement, CDialogEvents, Components.CDialog> = /*@__PURE__*/ createComponent<CDialogElement, CDialogEvents, Components.CDialog>({
    tagName: 'c-dialog',
    elementClass: CDialogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCShow: 'c-show',
        onCAfterShow: 'c-after-show',
        onCHide: 'c-hide',
        onCAfterHide: 'c-after-hide',
        onCInitialFocus: 'c-initial-focus',
        onCRequestClose: 'c-request-close'
    } as CDialogEvents,
    defineCustomElement: defineCDialog
});
