'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CDrawerCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CDrawer as CDrawerElement, defineCustomElement as defineCDrawer } from "@componentry-ui/stencil/dist/components/c-drawer.js";

export type CDrawerEvents = {
    onCShow: EventName<CDrawerCustomEvent<void>>,
    onCAfterShow: EventName<CDrawerCustomEvent<void>>,
    onCHide: EventName<CDrawerCustomEvent<void>>,
    onCAfterHide: EventName<CDrawerCustomEvent<void>>,
    onCInitialFocus: EventName<CDrawerCustomEvent<void>>,
    onCRequestClose: EventName<CDrawerCustomEvent<{ source: "close-button" | "keyboard" | "overlay"; }>>
};

export const CDrawer: StencilReactComponent<CDrawerElement, CDrawerEvents, Components.CDrawer> = /*@__PURE__*/ createComponent<CDrawerElement, CDrawerEvents, Components.CDrawer>({
    tagName: 'c-drawer',
    elementClass: CDrawerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCShow: 'cShow',
        onCAfterShow: 'cAfterShow',
        onCHide: 'cHide',
        onCAfterHide: 'cAfterHide',
        onCInitialFocus: 'cInitialFocus',
        onCRequestClose: 'cRequestClose'
    } as CDrawerEvents,
    defineCustomElement: defineCDrawer
});
