'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CIconButtonCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CIconButton as CIconButtonElement, defineCustomElement as defineCIconButton } from "@componentry-ui/stencil/dist/components/c-icon-button.js";

export type CIconButtonEvents = {
    onCBlur: EventName<CIconButtonCustomEvent<void>>,
    onCFocus: EventName<CIconButtonCustomEvent<void>>
};

export const CIconButton: StencilReactComponent<CIconButtonElement, CIconButtonEvents, Components.CIconButton> = /*@__PURE__*/ createComponent<CIconButtonElement, CIconButtonEvents, Components.CIconButton>({
    tagName: 'c-icon-button',
    elementClass: CIconButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCBlur: 'cBlur',
        onCFocus: 'cFocus'
    } as CIconButtonEvents,
    defineCustomElement: defineCIconButton
});
