'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CInputCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CInput as CInputElement, defineCustomElement as defineCInput } from "@componentry-ui/stencil/dist/components/c-input.js";

export type CInputEvents = {
    onCBlur: EventName<CInputCustomEvent<void>>,
    onCChange: EventName<CInputCustomEvent<void>>,
    onCClear: EventName<CInputCustomEvent<void>>,
    onCFocus: EventName<CInputCustomEvent<void>>,
    onCInput: EventName<CInputCustomEvent<void>>,
    onCInvalid: EventName<CInputCustomEvent<void>>
};

export const CInput: StencilReactComponent<CInputElement, CInputEvents, Components.CInput> = /*@__PURE__*/ createComponent<CInputElement, CInputEvents, Components.CInput>({
    tagName: 'c-input',
    elementClass: CInputElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCBlur: 'cBlur',
        onCChange: 'cChange',
        onCClear: 'cClear',
        onCFocus: 'cFocus',
        onCInput: 'cInput',
        onCInvalid: 'cInvalid'
    } as CInputEvents,
    defineCustomElement: defineCInput
});
