'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CMenuItemCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CMenuItem as CMenuItemElement, defineCustomElement as defineCMenuItem } from "@componentry-ui/stencil/dist/components/c-menu-item.js";

export type CMenuItemEvents = { onSlotchange: EventName<CMenuItemCustomEvent<void>> };

export const CMenuItem: StencilReactComponent<CMenuItemElement, CMenuItemEvents, Components.CMenuItem> = /*@__PURE__*/ createComponent<CMenuItemElement, CMenuItemEvents, Components.CMenuItem>({
    tagName: 'c-menu-item',
    elementClass: CMenuItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onSlotchange: 'slotchange' } as CMenuItemEvents,
    defineCustomElement: defineCMenuItem
});
