'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CMenuCustomEvent, type MenuSelectEventDetail } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CMenu as CMenuElement, defineCustomElement as defineCMenu } from "@componentry-ui/stencil/dist/components/c-menu.js";

export type CMenuEvents = { onCSelect: EventName<CMenuCustomEvent<MenuSelectEventDetail>> };

export const CMenu: StencilReactComponent<CMenuElement, CMenuEvents, Components.CMenu> = /*@__PURE__*/ createComponent<CMenuElement, CMenuEvents, Components.CMenu>({
    tagName: 'c-menu',
    elementClass: CMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCSelect: 'cSelect' } as CMenuEvents,
    defineCustomElement: defineCMenu
});
