'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CPopupCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CPopup as CPopupElement, defineCustomElement as defineCPopup } from "@componentry-ui/stencil/dist/components/c-popup.js";

export type CPopupEvents = { onCReposition: EventName<CPopupCustomEvent<void>> };

export const CPopup: StencilReactComponent<CPopupElement, CPopupEvents, Components.CPopup> = /*@__PURE__*/ createComponent<CPopupElement, CPopupEvents, Components.CPopup>({
    tagName: 'c-popup',
    elementClass: CPopupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onCReposition: 'cReposition' } as CPopupEvents,
    defineCustomElement: defineCPopup
});
