'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CProgressBar as CProgressBarElement, defineCustomElement as defineCProgressBar } from "@componentry-ui/stencil/dist/components/c-progress-bar.js";

export type CProgressBarEvents = NonNullable<unknown>;

export const CProgressBar: StencilReactComponent<CProgressBarElement, CProgressBarEvents, Components.CProgressBar> = /*@__PURE__*/ createComponent<CProgressBarElement, CProgressBarEvents, Components.CProgressBar>({
    tagName: 'c-progress-bar',
    elementClass: CProgressBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CProgressBarEvents,
    defineCustomElement: defineCProgressBar
});
