'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CRadioCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CRadio as CRadioElement, defineCustomElement as defineCRadio } from "@componentry-ui/stencil/dist/components/c-radio.js";

export type CRadioEvents = {
    onRadioFocus: EventName<CRadioCustomEvent<void>>,
    onRadioBlur: EventName<CRadioCustomEvent<void>>
};

export const CRadio: StencilReactComponent<CRadioElement, CRadioEvents, Components.CRadio> = /*@__PURE__*/ createComponent<CRadioElement, CRadioEvents, Components.CRadio>({
    tagName: 'c-radio',
    elementClass: CRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onRadioFocus: 'radioFocus',
        onRadioBlur: 'radioBlur'
    } as CRadioEvents,
    defineCustomElement: defineCRadio
});
