'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CRatingCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CRating as CRatingElement, defineCustomElement as defineCRating } from "@componentry-ui/stencil/dist/components/c-rating.js";

export type CRatingEvents = {
    onCRatingChange: EventName<CRatingCustomEvent<void>>,
    onCRatingHover: EventName<CRatingCustomEvent<{ phase: 'start' | 'move' | 'end'; value: number; }>>
};

export const CRating: StencilReactComponent<CRatingElement, CRatingEvents, Components.CRating> = /*@__PURE__*/ createComponent<CRatingElement, CRatingEvents, Components.CRating>({
    tagName: 'c-rating',
    elementClass: CRatingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCRatingChange: 'cRatingChange',
        onCRatingHover: 'cRatingHover'
    } as CRatingEvents,
    defineCustomElement: defineCRating
});
