'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CRadioGroupCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CRadioGroup as CRadioGroupElement, defineCustomElement as defineCRadioGroup } from "@componentry-ui/stencil/dist/components/c-radio-group.js";

export type CRadioGroupEvents = {
    onCChange: EventName<CRadioGroupCustomEvent<void>>,
    onCInput: EventName<CRadioGroupCustomEvent<void>>
};

export const CRadioGroup: StencilReactComponent<CRadioGroupElement, CRadioGroupEvents, Components.CRadioGroup> = /*@__PURE__*/ createComponent<CRadioGroupElement, CRadioGroupEvents, Components.CRadioGroup>({
    tagName: 'c-radio-group',
    elementClass: CRadioGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCChange: 'cChange',
        onCInput: 'cInput'
    } as CRadioGroupEvents,
    defineCustomElement: defineCRadioGroup
});
