'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import type { Components } from "@componentry-ui/stencil/dist/components";
import { CSpinner as CSpinnerElement, defineCustomElement as defineCSpinner } from "@componentry-ui/stencil/dist/components/c-spinner.js";

export type CSpinnerEvents = NonNullable<unknown>;

export const CSpinner: StencilReactComponent<CSpinnerElement, CSpinnerEvents, Components.CSpinner> = /*@__PURE__*/ createComponent<CSpinnerElement, CSpinnerEvents, Components.CSpinner>({
    tagName: 'c-spinner',
    elementClass: CSpinnerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as CSpinnerEvents,
    defineCustomElement: defineCSpinner
});
