'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type CTooltipCustomEvent } from "@componentry-ui/stencil";
import type { Components } from "@componentry-ui/stencil/dist/components";
import { CTooltip as CTooltipElement, defineCustomElement as defineCTooltip } from "@componentry-ui/stencil/dist/components/c-tooltip.js";

export type CTooltipEvents = {
    onCShow: EventName<CTooltipCustomEvent<void>>,
    onCAfterShow: EventName<CTooltipCustomEvent<void>>,
    onCHide: EventName<CTooltipCustomEvent<void>>,
    onCAfterHide: EventName<CTooltipCustomEvent<void>>
};

export const CTooltip: StencilReactComponent<CTooltipElement, CTooltipEvents, Components.CTooltip> = /*@__PURE__*/ createComponent<CTooltipElement, CTooltipEvents, Components.CTooltip>({
    tagName: 'c-tooltip',
    elementClass: CTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onCShow: 'cShow',
        onCAfterShow: 'cAfterShow',
        onCHide: 'cHide',
        onCAfterHide: 'cAfterHide'
    } as CTooltipEvents,
    defineCustomElement: defineCTooltip
});
