/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */
export { CAvatar } from "./c-avatar.js";
export { CButton } from "./c-button.js";
export { CInput } from "./c-input.js";
