import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsible: false,
      items: [
        { type: 'doc', id: 'intro', label: 'Introduction', className: 'sidebar-intro' },
        { type: 'doc', id: 'installation', label: 'Installation', className: 'sidebar-installation' },
      ],
    },
    {
      type: 'category',
      label: 'Foundations',
      collapsible: false,
      items: [
        { type: 'doc', id: 'theme', label: 'Themes & tokens', className: 'sidebar-theme' },
      ],
    },
    {
      type: 'category',
      label: 'Components',
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'components',
        },
      ],
    },
  ],
};

export default sidebars;
