/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * @summary Avatars are used to represent a person or object.
     * @event c-error - The image could not be loaded. This may because of an invalid URL,
     * a temporary network condition, or some unknown cause.
     * @csspart base - The component's base wrapper.
     * @csspart icon - The container that wraps the avatar's icon.
     * @csspart initials - The container that wraps the avatar's initials.
     * @csspart image - The avatar image. Only shown when the `image` attribute is set.
     * @cssproperty --size - The size of the avatar.
     */
    interface CAvatar {
        /**
          * The image source to use for the avatar.
          * @default ""
         */
        "image": string;
        /**
          * Initials to use as a fallback when no image is available (1–2 characters max recommended).
          * @default ""
         */
        "initials": string;
        /**
          * A label to use to describe the avatar to assistive devices.
          * @default ""
         */
        "label": string;
        /**
          * Indicates how the browser should load the image.
          * @default "eager"
         */
        "loading": "eager" | "lazy";
        /**
          * The shape of the avatar. Reflected to the host element so external CSS can target it via attribute.
          * @default "circle"
         */
        "shape": "circle" | "square" | "rounded";
    }
    /**
     * @summary Badges are used to draw attention and display statuses or counts.
     * @csspart base - The component's base wrapper.
     */
    interface CBadge {
        /**
          * Draws a pill-style badge with rounded edges.
          * @default false
         */
        "pill": boolean;
        /**
          * Makes the badge pulsate to draw attention.
          * @default false
         */
        "pulse": boolean;
        /**
          * The badge's theme variant.
          * @default "primary"
         */
        "variant": | "primary"
    | "success"
    | "neutral"
    | "warning"
    | "danger";
    }
    /**
     * @summary Buttons represent actions that are available to the user.
     * @csspart base - The component's base wrapper.
     * @csspart prefix - The container that wraps the prefix.
     * @csspart label - The button's label.
     * @csspart suffix - The container that wraps the suffix.
     * @csspart caret - The button's caret icon.
     * @csspart spinner - The spinner shown in loading state.
     */
    interface CButton {
        /**
          * Draws the button with a caret.
          * @default false
         */
        "caret": boolean;
        /**
          * Checks validity without showing a validation message.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Draws a circular icon button.
          * @default false
         */
        "circle": boolean;
        /**
          * Disables the button.
          * @default false
         */
        "disabled": boolean;
        /**
          * Tells the browser to download the linked file as this filename. Only used when `href` is present.
         */
        "download"?: string;
        /**
          * When set, renders as an `<a>` with this href instead of a `<button>`.
          * @default ""
         */
        "href": string;
        /**
          * Draws the button in a loading state.
          * @default false
         */
        "loading": boolean;
        /**
          * The name of the button, submitted as a name/value pair with form data.
          * @default ""
         */
        "name": string;
        /**
          * Draws an outlined button.
          * @default false
         */
        "outline": boolean;
        /**
          * Draws a pill-style button with rounded edges.
          * @default false
         */
        "pill": boolean;
        /**
          * Maps to the underlying link's `rel` attribute. Only used when `href` is present.
          * @default "noreferrer noopener"
         */
        "rel": string;
        /**
          * Removes focus from the button.
         */
        "removeFocus": () => Promise<void>;
        /**
          * Checks validity and shows the browser's validation message if invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Sets a custom validation message. Pass an empty string to restore validity.
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * Sets focus on the button.
         */
        "setFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * The button's size.
          * @default "medium"
         */
        "size": "small" | "medium" | "large";
        /**
          * Tells the browser where to open the link. Only used when `href` is present.
         */
        "target"?: "_blank" | "_parent" | "_self" | "_top";
        /**
          * Tooltip title passed through to the native element.
          * @default ""
         */
        "tooltip": string;
        /**
          * Simulates a click on the button.
         */
        "triggerClick": () => Promise<void>;
        /**
          * The type of button. Defaults to `button`. Set to `submit` to submit the surrounding form.
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
        /**
          * The value of the button, submitted as a pair with the button's name.
          * @default ""
         */
        "value": string;
        /**
          * The button's theme variant.
          * @default "default"
         */
        "variant": | "default"
    | "primary"
    | "success"
    | "neutral"
    | "warning"
    | "danger"
    | "text";
    }
    /**
     * @summary Checkboxes allow the user to toggle an option on or off.
     * @event c-blur    - Emitted when the checkbox loses focus.
     * @event c-change  - Emitted when the checked state changes.
     * @event c-focus   - Emitted when the checkbox gains focus.
     * @event c-input   - Emitted when the checkbox receives input.
     * @event c-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
     * @csspart base                   - The component's base wrapper.
     * @csspart control                - The square container that wraps the checkbox's checked state.
     * @csspart control--checked       - Matches the control part when the checkbox is checked.
     * @csspart control--indeterminate - Matches the control part when the checkbox is indeterminate.
     * @csspart checked-icon           - The checked icon element.
     * @csspart indeterminate-icon     - The indeterminate icon element.
     * @csspart label                  - The container that wraps the checkbox's label.
     * @csspart form-control-help-text - The help text's wrapper.
     */
    interface CCheckbox {
        /**
          * Removes focus from the checkbox.
         */
        "checkBlur": () => Promise<void>;
        /**
          * Passed through to the native input's title attribute.
          * @default ""
         */
        "checkBoxtitle": string;
        /**
          * Simulates a click on the checkbox.
         */
        "checkClick": () => Promise<void>;
        /**
          * Sets focus on the checkbox.
         */
        "checkFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * Checks for validity but does not show a validation message. Returns `true` when valid.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Draws the checkbox in a checked state.
          * @default false
         */
        "checked": boolean;
        /**
          * The default checked state. Primarily used for resetting the form control.
          * @default false
         */
        "defaultChecked": boolean;
        /**
          * Disables the checkbox.
          * @default false
         */
        "disabled": boolean;
        /**
          * Associates the control with a form element by id. The form must be in the same document or shadow root.
          * @default ""
         */
        "form": string;
        /**
          * The checkbox's help text. Use the `help-text` slot for HTML content.
          * @default ""
         */
        "helpText": string;
        /**
          * Draws the checkbox in an indeterminate state. Usually applied to "select all/none" checkboxes when associated checkboxes have a mix of checked and unchecked states.
          * @default false
         */
        "indeterminate": boolean;
        /**
          * The name of the checkbox, submitted as a name/value pair with form data.
          * @default ""
         */
        "name": string;
        /**
          * Checks for validity and shows the browser's validation message if the control is invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the checkbox a required field.
          * @default false
         */
        "required": boolean;
        /**
          * Sets a custom validation message. Pass an empty string to clear it.
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * The checkbox's size.
          * @default "medium"
         */
        "size": "small" | "medium" | "large";
        /**
          * The current value of the checkbox, submitted as a name/value pair with form data.
         */
        "value": string;
    }
    /**
     * @summary Inputs collect data from the user.
     * @event c-blur    - Emitted when the control loses focus.
     * @event c-change  - Emitted when an alteration to the control's value is committed by the user.
     * @event c-clear   - Emitted when the clear button is activated.
     * @event c-focus   - Emitted when the control gains focus.
     * @event c-input   - Emitted when the control receives input.
     * @event c-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
     * @csspart form-control           - The form control that wraps the label, input, and help text.
     * @csspart form-control-label     - The label's wrapper.
     * @csspart form-control-input     - The input's wrapper.
     * @csspart form-control-help-text - The help text's wrapper.
     * @csspart base                   - The component's base wrapper.
     * @csspart input                  - The internal <input> control.
     * @csspart prefix                 - The container that wraps the prefix.
     * @csspart clear-button           - The clear button.
     * @csspart password-toggle-button - The password toggle button.
     * @csspart suffix                 - The container that wraps the suffix.
     */
    interface CInput {
        "autocapitalize": | "off"
    | "none"
    | "on"
    | "sentences"
    | "words"
    | "characters";
        "autocomplete": string;
        "autocorrect": "off" | "on";
        "autofocus": boolean;
        /**
          * Checks for validity but does not show a validation message.
         */
        "checkValidity": () => Promise<boolean>;
        /**
          * Adds a clear button when the input is not empty.
          * @default false
         */
        "clearable": boolean;
        /**
          * Disables the input.
          * @default false
         */
        "disabled": boolean;
        "enterkeyhint": | "enter"
    | "done"
    | "go"
    | "next"
    | "previous"
    | "search"
    | "send";
        /**
          * Draws a filled input.
          * @default false
         */
        "filled": boolean;
        /**
          * The input's help text. If you need to display HTML, use the `help-text` slot instead.
          * @default ""
         */
        "helpText": string;
        /**
          * Title attribute passed through to the native input.
          * @default ""
         */
        "inputTitle": string;
        "inputmode": | "none"
    | "text"
    | "decimal"
    | "numeric"
    | "tel"
    | "search"
    | "email"
    | "url";
        /**
          * The input's label. If you need to display HTML, use the `label` slot instead.
          * @default ""
         */
        "label": string;
        "max": number | string;
        "maxlength": number;
        "min": number | string;
        "minlength": number;
        /**
          * The name of the input, submitted as a name/value pair with form data.
          * @default ""
         */
        "name": string;
        /**
          * Hides the browser's built-in increment/decrement spin buttons for number inputs.
          * @default false
         */
        "noSpinButtons": boolean;
        /**
          * Adds a button to toggle the password's visibility. Only applies to password types.
          * @default false
         */
        "passwordToggle": boolean;
        /**
          * A regular expression pattern to validate input against.
         */
        "pattern": string;
        /**
          * Draws a pill-style input with rounded edges.
          * @default false
         */
        "pill": boolean;
        /**
          * Placeholder text to show as a hint when the input is empty.
          * @default ""
         */
        "placeholder": string;
        /**
          * Makes the input readonly.
          * @default false
         */
        "readonly": boolean;
        /**
          * Removes focus from the input.
         */
        "removeFocus": () => Promise<void>;
        /**
          * Checks for validity and shows the browser's validation message if invalid.
         */
        "reportValidity": () => Promise<boolean>;
        /**
          * Makes the input a required field.
          * @default false
         */
        "required": boolean;
        /**
          * Selects all the text in the input.
         */
        "select": () => Promise<void>;
        /**
          * Sets a custom validation message. Pass an empty string to restore validity.
         */
        "setCustomValidity": (message: string) => Promise<void>;
        /**
          * Sets focus on the input.
         */
        "setFocus": (options?: FocusOptions) => Promise<void>;
        /**
          * Replaces a range of text with a new string.
         */
        "setRangeText": (replacement: string, start?: number, end?: number, selectMode?: "select" | "start" | "end" | "preserve") => Promise<void>;
        /**
          * Sets the start and end positions of the text selection (0-based).
         */
        "setSelectionRange": (selectionStart: number, selectionEnd: number, selectionDirection?: "forward" | "backward" | "none") => Promise<void>;
        /**
          * Displays the browser picker for an input element (only works if the browser supports it).
         */
        "showPicker": () => Promise<void>;
        /**
          * The input's size.
          * @default "medium"
         */
        "size": "small" | "medium" | "large";
        /**
          * Enables spell checking on the input.
          * @default true
         */
        "spellcheck": boolean;
        "step": number | "any";
        /**
          * Decrements the value of a numeric input type by the value of the step attribute.
         */
        "stepDown": () => Promise<void>;
        /**
          * Increments the value of a numeric input type by the value of the step attribute.
         */
        "stepUp": () => Promise<void>;
        /**
          * The type of input. Works the same as a native <input> element, but only a subset of types are supported. Defaults to `text`.
          * @default "text"
         */
        "type": | "date"
    | "datetime-local"
    | "email"
    | "number"
    | "password"
    | "search"
    | "tel"
    | "text"
    | "time"
    | "url";
        /**
          * The current value of the input.
          * @default ""
         */
        "value": string;
    }
}
export interface CAvatarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCAvatarElement;
}
export interface CButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCButtonElement;
}
export interface CCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCCheckboxElement;
}
export interface CInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCInputElement;
}
declare global {
    interface HTMLCAvatarElementEventMap {
        "cError": void;
    }
    /**
     * @summary Avatars are used to represent a person or object.
     * @event c-error - The image could not be loaded. This may because of an invalid URL,
     * a temporary network condition, or some unknown cause.
     * @csspart base - The component's base wrapper.
     * @csspart icon - The container that wraps the avatar's icon.
     * @csspart initials - The container that wraps the avatar's initials.
     * @csspart image - The avatar image. Only shown when the `image` attribute is set.
     * @cssproperty --size - The size of the avatar.
     */
    interface HTMLCAvatarElement extends Components.CAvatar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCAvatarElementEventMap>(type: K, listener: (this: HTMLCAvatarElement, ev: CAvatarCustomEvent<HTMLCAvatarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCAvatarElementEventMap>(type: K, listener: (this: HTMLCAvatarElement, ev: CAvatarCustomEvent<HTMLCAvatarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCAvatarElement: {
        prototype: HTMLCAvatarElement;
        new (): HTMLCAvatarElement;
    };
    /**
     * @summary Badges are used to draw attention and display statuses or counts.
     * @csspart base - The component's base wrapper.
     */
    interface HTMLCBadgeElement extends Components.CBadge, HTMLStencilElement {
    }
    var HTMLCBadgeElement: {
        prototype: HTMLCBadgeElement;
        new (): HTMLCBadgeElement;
    };
    interface HTMLCButtonElementEventMap {
        "cBlur": void;
        "cFocus": void;
        "cInvalid": void;
    }
    /**
     * @summary Buttons represent actions that are available to the user.
     * @csspart base - The component's base wrapper.
     * @csspart prefix - The container that wraps the prefix.
     * @csspart label - The button's label.
     * @csspart suffix - The container that wraps the suffix.
     * @csspart caret - The button's caret icon.
     * @csspart spinner - The spinner shown in loading state.
     */
    interface HTMLCButtonElement extends Components.CButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCButtonElementEventMap>(type: K, listener: (this: HTMLCButtonElement, ev: CButtonCustomEvent<HTMLCButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCButtonElementEventMap>(type: K, listener: (this: HTMLCButtonElement, ev: CButtonCustomEvent<HTMLCButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCButtonElement: {
        prototype: HTMLCButtonElement;
        new (): HTMLCButtonElement;
    };
    interface HTMLCCheckboxElementEventMap {
        "cBlur": void;
        "cChange": void;
        "cFocus": void;
        "cInput": void;
        "cInvalid": void;
    }
    /**
     * @summary Checkboxes allow the user to toggle an option on or off.
     * @event c-blur    - Emitted when the checkbox loses focus.
     * @event c-change  - Emitted when the checked state changes.
     * @event c-focus   - Emitted when the checkbox gains focus.
     * @event c-input   - Emitted when the checkbox receives input.
     * @event c-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
     * @csspart base                   - The component's base wrapper.
     * @csspart control                - The square container that wraps the checkbox's checked state.
     * @csspart control--checked       - Matches the control part when the checkbox is checked.
     * @csspart control--indeterminate - Matches the control part when the checkbox is indeterminate.
     * @csspart checked-icon           - The checked icon element.
     * @csspart indeterminate-icon     - The indeterminate icon element.
     * @csspart label                  - The container that wraps the checkbox's label.
     * @csspart form-control-help-text - The help text's wrapper.
     */
    interface HTMLCCheckboxElement extends Components.CCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCCheckboxElementEventMap>(type: K, listener: (this: HTMLCCheckboxElement, ev: CCheckboxCustomEvent<HTMLCCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCCheckboxElementEventMap>(type: K, listener: (this: HTMLCCheckboxElement, ev: CCheckboxCustomEvent<HTMLCCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCCheckboxElement: {
        prototype: HTMLCCheckboxElement;
        new (): HTMLCCheckboxElement;
    };
    interface HTMLCInputElementEventMap {
        "cBlur": void;
        "cChange": void;
        "cClear": void;
        "cFocus": void;
        "cInput": void;
        "cInvalid": void;
    }
    /**
     * @summary Inputs collect data from the user.
     * @event c-blur    - Emitted when the control loses focus.
     * @event c-change  - Emitted when an alteration to the control's value is committed by the user.
     * @event c-clear   - Emitted when the clear button is activated.
     * @event c-focus   - Emitted when the control gains focus.
     * @event c-input   - Emitted when the control receives input.
     * @event c-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
     * @csspart form-control           - The form control that wraps the label, input, and help text.
     * @csspart form-control-label     - The label's wrapper.
     * @csspart form-control-input     - The input's wrapper.
     * @csspart form-control-help-text - The help text's wrapper.
     * @csspart base                   - The component's base wrapper.
     * @csspart input                  - The internal <input> control.
     * @csspart prefix                 - The container that wraps the prefix.
     * @csspart clear-button           - The clear button.
     * @csspart password-toggle-button - The password toggle button.
     * @csspart suffix                 - The container that wraps the suffix.
     */
    interface HTMLCInputElement extends Components.CInput, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCInputElementEventMap>(type: K, listener: (this: HTMLCInputElement, ev: CInputCustomEvent<HTMLCInputElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCInputElementEventMap>(type: K, listener: (this: HTMLCInputElement, ev: CInputCustomEvent<HTMLCInputElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCInputElement: {
        prototype: HTMLCInputElement;
        new (): HTMLCInputElement;
    };
    interface HTMLElementTagNameMap {
        "c-avatar": HTMLCAvatarElement;
        "c-badge": HTMLCBadgeElement;
        "c-button": HTMLCButtonElement;
        "c-checkbox": HTMLCCheckboxElement;
        "c-input": HTMLCInputElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    /**
     * @summary Avatars are used to represent a person or object.
     * @event c-error - The image could not be loaded. This may because of an invalid URL,
     * a temporary network condition, or some unknown cause.
     * @csspart base - The component's base wrapper.
     * @csspart icon - The container that wraps the avatar's icon.
     * @csspart initials - The container that wraps the avatar's initials.
     * @csspart image - The avatar image. Only shown when the `image` attribute is set.
     * @cssproperty --size - The size of the avatar.
     */
    interface CAvatar {
        /**
          * The image source to use for the avatar.
          * @default ""
         */
        "image"?: string;
        /**
          * Initials to use as a fallback when no image is available (1–2 characters max recommended).
          * @default ""
         */
        "initials"?: string;
        /**
          * A label to use to describe the avatar to assistive devices.
          * @default ""
         */
        "label"?: string;
        /**
          * Indicates how the browser should load the image.
          * @default "eager"
         */
        "loading"?: "eager" | "lazy";
        /**
          * Emitted when the image fails to load.
         */
        "onCError"?: (event: CAvatarCustomEvent<void>) => void;
        /**
          * The shape of the avatar. Reflected to the host element so external CSS can target it via attribute.
          * @default "circle"
         */
        "shape"?: "circle" | "square" | "rounded";
    }
    /**
     * @summary Badges are used to draw attention and display statuses or counts.
     * @csspart base - The component's base wrapper.
     */
    interface CBadge {
        /**
          * Draws a pill-style badge with rounded edges.
          * @default false
         */
        "pill"?: boolean;
        /**
          * Makes the badge pulsate to draw attention.
          * @default false
         */
        "pulse"?: boolean;
        /**
          * The badge's theme variant.
          * @default "primary"
         */
        "variant"?: | "primary"
    | "success"
    | "neutral"
    | "warning"
    | "danger";
    }
    /**
     * @summary Buttons represent actions that are available to the user.
     * @csspart base - The component's base wrapper.
     * @csspart prefix - The container that wraps the prefix.
     * @csspart label - The button's label.
     * @csspart suffix - The container that wraps the suffix.
     * @csspart caret - The button's caret icon.
     * @csspart spinner - The spinner shown in loading state.
     */
    interface CButton {
        /**
          * Draws the button with a caret.
          * @default false
         */
        "caret"?: boolean;
        /**
          * Draws a circular icon button.
          * @default false
         */
        "circle"?: boolean;
        /**
          * Disables the button.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Tells the browser to download the linked file as this filename. Only used when `href` is present.
         */
        "download"?: string;
        /**
          * When set, renders as an `<a>` with this href instead of a `<button>`.
          * @default ""
         */
        "href"?: string;
        /**
          * Draws the button in a loading state.
          * @default false
         */
        "loading"?: boolean;
        /**
          * The name of the button, submitted as a name/value pair with form data.
          * @default ""
         */
        "name"?: string;
        /**
          * Emitted when the button loses focus.
         */
        "onCBlur"?: (event: CButtonCustomEvent<void>) => void;
        /**
          * Emitted when the button gains focus.
         */
        "onCFocus"?: (event: CButtonCustomEvent<void>) => void;
        /**
          * Emitted when the form control fails constraint validation.
         */
        "onCInvalid"?: (event: CButtonCustomEvent<void>) => void;
        /**
          * Draws an outlined button.
          * @default false
         */
        "outline"?: boolean;
        /**
          * Draws a pill-style button with rounded edges.
          * @default false
         */
        "pill"?: boolean;
        /**
          * Maps to the underlying link's `rel` attribute. Only used when `href` is present.
          * @default "noreferrer noopener"
         */
        "rel"?: string;
        /**
          * The button's size.
          * @default "medium"
         */
        "size"?: "small" | "medium" | "large";
        /**
          * Tells the browser where to open the link. Only used when `href` is present.
         */
        "target"?: "_blank" | "_parent" | "_self" | "_top";
        /**
          * Tooltip title passed through to the native element.
          * @default ""
         */
        "tooltip"?: string;
        /**
          * The type of button. Defaults to `button`. Set to `submit` to submit the surrounding form.
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * The value of the button, submitted as a pair with the button's name.
          * @default ""
         */
        "value"?: string;
        /**
          * The button's theme variant.
          * @default "default"
         */
        "variant"?: | "default"
    | "primary"
    | "success"
    | "neutral"
    | "warning"
    | "danger"
    | "text";
    }
    /**
     * @summary Checkboxes allow the user to toggle an option on or off.
     * @event c-blur    - Emitted when the checkbox loses focus.
     * @event c-change  - Emitted when the checked state changes.
     * @event c-focus   - Emitted when the checkbox gains focus.
     * @event c-input   - Emitted when the checkbox receives input.
     * @event c-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
     * @csspart base                   - The component's base wrapper.
     * @csspart control                - The square container that wraps the checkbox's checked state.
     * @csspart control--checked       - Matches the control part when the checkbox is checked.
     * @csspart control--indeterminate - Matches the control part when the checkbox is indeterminate.
     * @csspart checked-icon           - The checked icon element.
     * @csspart indeterminate-icon     - The indeterminate icon element.
     * @csspart label                  - The container that wraps the checkbox's label.
     * @csspart form-control-help-text - The help text's wrapper.
     */
    interface CCheckbox {
        /**
          * Passed through to the native input's title attribute.
          * @default ""
         */
        "checkBoxtitle"?: string;
        /**
          * Draws the checkbox in a checked state.
          * @default false
         */
        "checked"?: boolean;
        /**
          * The default checked state. Primarily used for resetting the form control.
          * @default false
         */
        "defaultChecked"?: boolean;
        /**
          * Disables the checkbox.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Associates the control with a form element by id. The form must be in the same document or shadow root.
          * @default ""
         */
        "form"?: string;
        /**
          * The checkbox's help text. Use the `help-text` slot for HTML content.
          * @default ""
         */
        "helpText"?: string;
        /**
          * Draws the checkbox in an indeterminate state. Usually applied to "select all/none" checkboxes when associated checkboxes have a mix of checked and unchecked states.
          * @default false
         */
        "indeterminate"?: boolean;
        /**
          * The name of the checkbox, submitted as a name/value pair with form data.
          * @default ""
         */
        "name"?: string;
        "onCBlur"?: (event: CCheckboxCustomEvent<void>) => void;
        "onCChange"?: (event: CCheckboxCustomEvent<void>) => void;
        "onCFocus"?: (event: CCheckboxCustomEvent<void>) => void;
        "onCInput"?: (event: CCheckboxCustomEvent<void>) => void;
        "onCInvalid"?: (event: CCheckboxCustomEvent<void>) => void;
        /**
          * Makes the checkbox a required field.
          * @default false
         */
        "required"?: boolean;
        /**
          * The checkbox's size.
          * @default "medium"
         */
        "size"?: "small" | "medium" | "large";
        /**
          * The current value of the checkbox, submitted as a name/value pair with form data.
         */
        "value": string;
    }
    /**
     * @summary Inputs collect data from the user.
     * @event c-blur    - Emitted when the control loses focus.
     * @event c-change  - Emitted when an alteration to the control's value is committed by the user.
     * @event c-clear   - Emitted when the clear button is activated.
     * @event c-focus   - Emitted when the control gains focus.
     * @event c-input   - Emitted when the control receives input.
     * @event c-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
     * @csspart form-control           - The form control that wraps the label, input, and help text.
     * @csspart form-control-label     - The label's wrapper.
     * @csspart form-control-input     - The input's wrapper.
     * @csspart form-control-help-text - The help text's wrapper.
     * @csspart base                   - The component's base wrapper.
     * @csspart input                  - The internal <input> control.
     * @csspart prefix                 - The container that wraps the prefix.
     * @csspart clear-button           - The clear button.
     * @csspart password-toggle-button - The password toggle button.
     * @csspart suffix                 - The container that wraps the suffix.
     */
    interface CInput {
        "autocapitalize": | "off"
    | "none"
    | "on"
    | "sentences"
    | "words"
    | "characters";
        "autocomplete": string;
        "autocorrect": "off" | "on";
        "autofocus": boolean;
        /**
          * Adds a clear button when the input is not empty.
          * @default false
         */
        "clearable"?: boolean;
        /**
          * Disables the input.
          * @default false
         */
        "disabled"?: boolean;
        "enterkeyhint": | "enter"
    | "done"
    | "go"
    | "next"
    | "previous"
    | "search"
    | "send";
        /**
          * Draws a filled input.
          * @default false
         */
        "filled"?: boolean;
        /**
          * The input's help text. If you need to display HTML, use the `help-text` slot instead.
          * @default ""
         */
        "helpText"?: string;
        /**
          * Title attribute passed through to the native input.
          * @default ""
         */
        "inputTitle"?: string;
        "inputmode": | "none"
    | "text"
    | "decimal"
    | "numeric"
    | "tel"
    | "search"
    | "email"
    | "url";
        /**
          * The input's label. If you need to display HTML, use the `label` slot instead.
          * @default ""
         */
        "label"?: string;
        "max": number | string;
        "maxlength": number;
        "min": number | string;
        "minlength": number;
        /**
          * The name of the input, submitted as a name/value pair with form data.
          * @default ""
         */
        "name"?: string;
        /**
          * Hides the browser's built-in increment/decrement spin buttons for number inputs.
          * @default false
         */
        "noSpinButtons"?: boolean;
        "onCBlur"?: (event: CInputCustomEvent<void>) => void;
        "onCChange"?: (event: CInputCustomEvent<void>) => void;
        "onCClear"?: (event: CInputCustomEvent<void>) => void;
        "onCFocus"?: (event: CInputCustomEvent<void>) => void;
        "onCInput"?: (event: CInputCustomEvent<void>) => void;
        "onCInvalid"?: (event: CInputCustomEvent<void>) => void;
        /**
          * Adds a button to toggle the password's visibility. Only applies to password types.
          * @default false
         */
        "passwordToggle"?: boolean;
        /**
          * A regular expression pattern to validate input against.
         */
        "pattern": string;
        /**
          * Draws a pill-style input with rounded edges.
          * @default false
         */
        "pill"?: boolean;
        /**
          * Placeholder text to show as a hint when the input is empty.
          * @default ""
         */
        "placeholder"?: string;
        /**
          * Makes the input readonly.
          * @default false
         */
        "readonly"?: boolean;
        /**
          * Makes the input a required field.
          * @default false
         */
        "required"?: boolean;
        /**
          * The input's size.
          * @default "medium"
         */
        "size"?: "small" | "medium" | "large";
        /**
          * Enables spell checking on the input.
          * @default true
         */
        "spellcheck"?: boolean;
        "step": number | "any";
        /**
          * The type of input. Works the same as a native <input> element, but only a subset of types are supported. Defaults to `text`.
          * @default "text"
         */
        "type"?: | "date"
    | "datetime-local"
    | "email"
    | "number"
    | "password"
    | "search"
    | "tel"
    | "text"
    | "time"
    | "url";
        /**
          * The current value of the input.
          * @default ""
         */
        "value"?: string;
    }

    interface CAvatarAttributes {
        "image": string;
        "label": string;
        "initials": string;
        "loading": "eager" | "lazy";
        "shape": "circle" | "square" | "rounded";
    }
    interface CBadgeAttributes {
        "variant": | "primary"
    | "success"
    | "neutral"
    | "warning"
    | "danger";
        "pill": boolean;
        "pulse": boolean;
    }
    interface CButtonAttributes {
        "variant": | "default"
    | "primary"
    | "success"
    | "neutral"
    | "warning"
    | "danger"
    | "text";
        "size": "small" | "medium" | "large";
        "caret": boolean;
        "disabled": boolean;
        "loading": boolean;
        "outline": boolean;
        "pill": boolean;
        "circle": boolean;
        "type": "button" | "submit" | "reset";
        "name": string;
        "value": string;
        "href": string;
        "target": "_blank" | "_parent" | "_self" | "_top";
        "rel": string;
        "download": string;
        "tooltip": string;
    }
    interface CCheckboxAttributes {
        "checkBoxtitle": string;
        "name": string;
        "value": string;
        "size": "small" | "medium" | "large";
        "disabled": boolean;
        "checked": boolean;
        "indeterminate": boolean;
        "defaultChecked": boolean;
        "form": string;
        "required": boolean;
        "helpText": string;
    }
    interface CInputAttributes {
        "type": | "date"
    | "datetime-local"
    | "email"
    | "number"
    | "password"
    | "search"
    | "tel"
    | "text"
    | "time"
    | "url";
        "name": string;
        "value": string;
        "size": "small" | "medium" | "large";
        "filled": boolean;
        "pill": boolean;
        "label": string;
        "helpText": string;
        "clearable": boolean;
        "disabled": boolean;
        "placeholder": string;
        "readonly": boolean;
        "passwordToggle": boolean;
        "noSpinButtons": boolean;
        "required": boolean;
        "pattern": string;
        "minlength": number;
        "maxlength": number;
        "min": string;
        "max": string;
        "step": string;
        "autocapitalize": | "off"
    | "none"
    | "on"
    | "sentences"
    | "words"
    | "characters";
        "autocorrect": "off" | "on";
        "autocomplete": string;
        "autofocus": boolean;
        "enterkeyhint": | "enter"
    | "done"
    | "go"
    | "next"
    | "previous"
    | "search"
    | "send";
        "inputmode": | "none"
    | "text"
    | "decimal"
    | "numeric"
    | "tel"
    | "search"
    | "email"
    | "url";
        "spellcheck": boolean;
        "inputTitle": string;
    }

    interface IntrinsicElements {
        "c-avatar": Omit<CAvatar, keyof CAvatarAttributes> & { [K in keyof CAvatar & keyof CAvatarAttributes]?: CAvatar[K] } & { [K in keyof CAvatar & keyof CAvatarAttributes as `attr:${K}`]?: CAvatarAttributes[K] } & { [K in keyof CAvatar & keyof CAvatarAttributes as `prop:${K}`]?: CAvatar[K] };
        "c-badge": Omit<CBadge, keyof CBadgeAttributes> & { [K in keyof CBadge & keyof CBadgeAttributes]?: CBadge[K] } & { [K in keyof CBadge & keyof CBadgeAttributes as `attr:${K}`]?: CBadgeAttributes[K] } & { [K in keyof CBadge & keyof CBadgeAttributes as `prop:${K}`]?: CBadge[K] };
        "c-button": Omit<CButton, keyof CButtonAttributes> & { [K in keyof CButton & keyof CButtonAttributes]?: CButton[K] } & { [K in keyof CButton & keyof CButtonAttributes as `attr:${K}`]?: CButtonAttributes[K] } & { [K in keyof CButton & keyof CButtonAttributes as `prop:${K}`]?: CButton[K] };
        "c-checkbox": Omit<CCheckbox, keyof CCheckboxAttributes> & { [K in keyof CCheckbox & keyof CCheckboxAttributes]?: CCheckbox[K] } & { [K in keyof CCheckbox & keyof CCheckboxAttributes as `attr:${K}`]?: CCheckboxAttributes[K] } & { [K in keyof CCheckbox & keyof CCheckboxAttributes as `prop:${K}`]?: CCheckbox[K] } & OneOf<"value", CCheckbox["value"], CCheckboxAttributes["value"]>;
        "c-input": Omit<CInput, keyof CInputAttributes> & { [K in keyof CInput & keyof CInputAttributes]?: CInput[K] } & { [K in keyof CInput & keyof CInputAttributes as `attr:${K}`]?: CInputAttributes[K] } & { [K in keyof CInput & keyof CInputAttributes as `prop:${K}`]?: CInput[K] } & OneOf<"pattern", CInput["pattern"], CInputAttributes["pattern"]> & OneOf<"minlength", CInput["minlength"], CInputAttributes["minlength"]> & OneOf<"maxlength", CInput["maxlength"], CInputAttributes["maxlength"]> & OneOf<"min", CInput["min"], CInputAttributes["min"]> & OneOf<"max", CInput["max"], CInputAttributes["max"]> & OneOf<"step", CInput["step"], CInputAttributes["step"]> & OneOf<"autocapitalize", CInput["autocapitalize"], CInputAttributes["autocapitalize"]> & OneOf<"autocorrect", CInput["autocorrect"], CInputAttributes["autocorrect"]> & OneOf<"autocomplete", CInput["autocomplete"], CInputAttributes["autocomplete"]> & OneOf<"autofocus", CInput["autofocus"], CInputAttributes["autofocus"]> & OneOf<"enterkeyhint", CInput["enterkeyhint"], CInputAttributes["enterkeyhint"]> & OneOf<"inputmode", CInput["inputmode"], CInputAttributes["inputmode"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * @summary Avatars are used to represent a person or object.
             * @event c-error - The image could not be loaded. This may because of an invalid URL,
             * a temporary network condition, or some unknown cause.
             * @csspart base - The component's base wrapper.
             * @csspart icon - The container that wraps the avatar's icon.
             * @csspart initials - The container that wraps the avatar's initials.
             * @csspart image - The avatar image. Only shown when the `image` attribute is set.
             * @cssproperty --size - The size of the avatar.
             */
            "c-avatar": LocalJSX.IntrinsicElements["c-avatar"] & JSXBase.HTMLAttributes<HTMLCAvatarElement>;
            /**
             * @summary Badges are used to draw attention and display statuses or counts.
             * @csspart base - The component's base wrapper.
             */
            "c-badge": LocalJSX.IntrinsicElements["c-badge"] & JSXBase.HTMLAttributes<HTMLCBadgeElement>;
            /**
             * @summary Buttons represent actions that are available to the user.
             * @csspart base - The component's base wrapper.
             * @csspart prefix - The container that wraps the prefix.
             * @csspart label - The button's label.
             * @csspart suffix - The container that wraps the suffix.
             * @csspart caret - The button's caret icon.
             * @csspart spinner - The spinner shown in loading state.
             */
            "c-button": LocalJSX.IntrinsicElements["c-button"] & JSXBase.HTMLAttributes<HTMLCButtonElement>;
            /**
             * @summary Checkboxes allow the user to toggle an option on or off.
             * @event c-blur    - Emitted when the checkbox loses focus.
             * @event c-change  - Emitted when the checked state changes.
             * @event c-focus   - Emitted when the checkbox gains focus.
             * @event c-input   - Emitted when the checkbox receives input.
             * @event c-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
             * @csspart base                   - The component's base wrapper.
             * @csspart control                - The square container that wraps the checkbox's checked state.
             * @csspart control--checked       - Matches the control part when the checkbox is checked.
             * @csspart control--indeterminate - Matches the control part when the checkbox is indeterminate.
             * @csspart checked-icon           - The checked icon element.
             * @csspart indeterminate-icon     - The indeterminate icon element.
             * @csspart label                  - The container that wraps the checkbox's label.
             * @csspart form-control-help-text - The help text's wrapper.
             */
            "c-checkbox": LocalJSX.IntrinsicElements["c-checkbox"] & JSXBase.HTMLAttributes<HTMLCCheckboxElement>;
            /**
             * @summary Inputs collect data from the user.
             * @event c-blur    - Emitted when the control loses focus.
             * @event c-change  - Emitted when an alteration to the control's value is committed by the user.
             * @event c-clear   - Emitted when the clear button is activated.
             * @event c-focus   - Emitted when the control gains focus.
             * @event c-input   - Emitted when the control receives input.
             * @event c-invalid - Emitted when the form control has been checked for validity and its constraints aren't satisfied.
             * @csspart form-control           - The form control that wraps the label, input, and help text.
             * @csspart form-control-label     - The label's wrapper.
             * @csspart form-control-input     - The input's wrapper.
             * @csspart form-control-help-text - The help text's wrapper.
             * @csspart base                   - The component's base wrapper.
             * @csspart input                  - The internal <input> control.
             * @csspart prefix                 - The container that wraps the prefix.
             * @csspart clear-button           - The clear button.
             * @csspart password-toggle-button - The password toggle button.
             * @csspart suffix                 - The container that wraps the suffix.
             */
            "c-input": LocalJSX.IntrinsicElements["c-input"] & JSXBase.HTMLAttributes<HTMLCInputElement>;
        }
    }
}
